import styled from 'styled-components';
import Head from "next/head";
import Image from "next/image";
import BarraNav from "@/components/layout/header/barraNav";
import Saludo from "@/components/layout/main/saludo";
import Contador from "@/components/pages/home/footer/contador";

const StyledHeader = styled.header`
  background-color: #FFEFD5;
  color: #black;
  padding: 20px;
`;

export default function Home() {
  return (
    <>
    <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://fonts.googleapis.com/css2?family=Inter&display=swap" rel="stylesheet" />
    </Head>
    <StyledHeader>
      <BarraNav/>
    </StyledHeader>
    <main>
      <Saludo/>
    </main>
    <footer>
      <Contador/>
    </footer>
    </>
  );
}